#!/bin/sh

# Compile a Curry program with idcompiler and ghc
SYSDIR=`dirname "$0"`
LIBDIR=$SYSDIR/lib
RTSDIR=$SYSDIR/runtime

OPTIM=
MAINOP="eval"
MAINPREFIX="nd_C_"
MAINNAME="main"
IDSUPPLYDIR=$RTSDIR/idsupplyinteger

while [ $# -gt 1 ] ; do
  case $1 in
    -e         ) shift; MAINNAME="$1" ;;
    -o         ) OPTIM="-O2" ;;
    -d         ) MAINOP="evalD" ; MAINPREFIX="d_C_" ;;
    -io        ) MAINOP="evalIO" ;;
    --prdfs    ) MAINOP="prdfs" ;;
    --dfs      ) MAINOP="printDFS" ;;
    --dfs1     ) MAINOP="printDFS1" ;;
    --dfsi     ) MAINOP="printDFSi" ;;
    --bfs      ) MAINOP="printBFS" ;;
    --bfs1     ) MAINOP="printBFS1" ;;
    --bfsi     ) MAINOP="printBFSi" ;;
    --ids      ) MAINOP="printIDS" ;;
    --ids1     ) MAINOP="printIDS1" ;;
    --idsi     ) MAINOP="printIDSi" ;;
    --idsupply ) shift ; IDSUPPLYDIR=$RTSDIR/idsupply$1 ;;
    * ) echo ERROR: Illegal option: "$@" >&2 ; exit 1 ;;
  esac
  shift
done
if [ $MAINOP = "evalIO" -a $MAINPREFIX = "d_C_" ] ; then
  MAINOP="evalDIO"
fi
MAIN="$MAINOP $MAINPREFIX$MAINNAME"

if [ $# != 1 ] ; then
  echo >&2
  echo "Usage: compilecurry [<options>] <progname>" >&2
  echo >&2
  echo "Compile Curry program stored in <progname>.(l)curry" >&2
  echo >&2
  echo "<options> is a sequence of:"  >&2
  echo "-e n    : use n (instead of main) as main operation to evaluate" >&2
  echo "-o      : compile with optimizations" >&2
  echo "-d      : call deterministic version of main goal" >&2
  echo "-io     : call main goal of IO type" >&2
  echo "--prdfs : evaluate non-det.(!) main goal and print results via dfs" >&2
  echo "--dfs   : evaluate non-det.(!) main goal and print results via dfs" >&2
  echo "--dfs1  : evaluate non-det.(!) main goal and print first result via dfs" >&2
  echo "--dfsi  : evaluate non-det.(!) main goal and print results on request via dfs" >&2
  echo "--bfs   : evaluate non-det.(!) main goal and print results via bfs" >&2
  echo "--bfs1  : evaluate non-det.(!) main goal and print first result via bfs" >&2
  echo "--bfsi  : evaluate non-det.(!) main goal and print results on request via bfs" >&2
  echo "--ids   : evaluate non-det.(!) main goal and print results via ids" >&2
  echo "--ids1  : evaluate non-det.(!) main goal and print first result via ids" >&2
  echo "--idsi  : evaluate non-det.(!) main goal and print results on request via ids" >&2
  echo "--idsupply I : choose implementation I for choice identifiers" >&2
  echo "               (where I=integer (default) or I=ioref)" >&2
  exit 1
fi

PROG=$1
PROG=`expr $PROG : '\(.*\)\.lcurry' \| $PROG`
PROG=`expr $PROG : '\(.*\)\.curry' \| $PROG`

$SYSDIR/idc -q -i$LIBDIR -o. $1

echo "module Main where" > Main.hs
echo "import Basics" >> Main.hs
echo "import Curry_$PROG" >> Main.hs
echo "main = ${MAIN}" >> Main.hs
ghc $OPTIM --make -fforce-recomp -i$RTSDIR:$IDSUPPLYDIR:$LIBDIR Main.hs
# auch: -funbox-strict-fields
