#!/bin/sh

# Compile a Curry program with idcompiler and ghc
SYSDIR=`dirname "$0"`
OPTIM=
if [ "$1" = "-o" ] ; then # compile with optimizations
  OPTIM="-O2" ; shift
fi
MAIN="eval nd_C_main >>= print"
if [ "$1" = "-d" ] ; then # call deterministic version of main goal
  MAIN="print d_C_main" ; shift
fi
PROG=$1
PROG=`expr $PROG : '\(.*\)\.lcurry' \| $PROG`
PROG=`expr $PROG : '\(.*\)\.curry' \| $PROG`

$SYSDIR/idc -q -i $SYSDIR/examples/ $1
echo "module Main where" > Main.hs
echo "import Basics (eval)" >> Main.hs
echo "import Curry_$PROG" >> Main.hs
echo "main = ${MAIN}" >> Main.hs
ghc $OPTIM --make -fforce-recomp -i$SYSDIR Main.hs
# auch: -funbox-strict-fields
