#!/bin/sh

# Compile a Curry program with idcompiler and load into ghci
SYSDIR=`dirname "$0"`
IDSUPPLYDIR=$SYSDIR/idsupplyinteger
PRELUDEDIR=$SYSDIR/lib
PROG=$1
PROG=`expr $PROG : '\(.*\)\.lcurry' \| $PROG`
PROG=`expr $PROG : '\(.*\)\.curry' \| $PROG`

$SYSDIR/idc -q -i $PRELUDEDIR $1 && ghci -i$SYSDIR:$IDSUPPLYDIR:$PRELUDEDIR Curry_$PROG.hs
