#!/bin/sh

# Compile a Curry program with idcompiler and load into ghci
SYSDIR=`dirname "$0"`
RTSDIR=$SYSDIR/runtime
IDSUPPLYDIR=$RTSDIR/idsupplyinteger
LIBDIR=$SYSDIR/lib
PROG=$1
PROG=`expr $PROG : '\(.*\)\.lcurry' \| $PROG`
PROG=`expr $PROG : '\(.*\)\.curry' \| $PROG`

$SYSDIR/idc -q -i$LIBDIR -o. $1 && ghci -i$RTSDIR:$IDSUPPLYDIR:$LIBDIR Curry_$PROG.hs
