#!/bin/sh

# Compile and load into ghci
SYSDIR=`dirname "$0"`
PROG=$1
PROG=`expr $PROG : '\(.*\)\.lcurry' \| $PROG`
PROG=`expr $PROG : '\(.*\)\.curry' \| $PROG`

$SYSDIR/idc $1 && ghci -i$SYSDIR Curry_$PROG.hs
