#!/bin/sh
# script to execute unit tests for Curry
CURRYHOME=..
CURRYBIN=$CURRYHOME/bin

TESTPARAMS="--window"
if [ "$1" = "--nogui" ] ; then
  TESTPARAMS=
fi

# test for basic language features
TESTLANG="testFunctional testInfinite testHigher testNondet testCase testLetRec testNarr testUnification testNonLinearPattern testNonStrictUnif testFuncPattern testAsPattern testPolySubExp"

# test for standard libraries
TESTLIBS="testPrelude testArray testCombinatorial testDequeue testDirectory testFiniteMap testFlatCurryGoodies testGlobal testInteger testIO testIOExts testKeyDatabaseSQLite testList testRedBlackTree testSetFunctions testSort testSystem testTraversal testUnsafeSearchTree testExpTypeInference"
# further tests for the future:
# testGlobalVariable # not yet implemented
# testFlatCurryXML # causes memory overflow

# test tools
TESTTOOLS="testData2Xml"

ALLTESTS="$TESTLANG $TESTLIBS $TESTTOOLS"

# clean up before
$KICS2BIN/cleancurry

# execute all unit tests:
echo "Executing unit tests for back end $BACKEND..."
$CURRYBIN/currytest $TESTPARAMS $ALLTESTS
